Aruche-code/kd-reserve

- app/api/test/route.ts
> add delete api

- app/(root)/components/AuthForm.tsx
- app/api/auth/[...nextauth]/route.ts
- app/api/register/route.tsx
- app/api/test/[id]/route.ts
- app/libs/prismadb.ts
- package-lock.json
- package.json
- prisma/schema.prisma
> Feature tomo

- app/(root)/components/AuthForm.tsx
- app/(root)/page.tsx
- app/(root)/staff/layout.tsx
- app/(root)/staff/page.tsx
- app/(root)/student/layout.tsx
- app/(root)/student/page.tsx
- app/api/auth/[...nextauth]/route.ts
- app/api/register/route.ts
- app/components/sidebar/Sidebar.tsx
- app/components/sidebar/Spare.tsx
- app/components/sidebar/StaffSidebar.tsx
- app/components/sidebar/StudentSidebar.tsx
- app/layout.tsx
- app/users/page.tsx
生徒画面はstudentに職員画面はstaffへ移動させてください
> 移行できますので後はよろしく

- app/api/hagi/StaffNg/route.ts
- prisma/schema.prisma
StaffNgモデル定義の修正とテスト用APIのUpdateとDeleteを追加しました。確認お願いします。
> add NG日用モデルの修正, テスト用APIのCRUD全ての作成

- app/api/hagi/StaffNg/route.ts
- app/api/hagi/WatingList/route.ts
- prisma/schema.prisma
承認待ちモデルと予約リストのモデルの定義、テスト用APIのファイル作成などを行いました。確認お願いします。
> add 承認待ちモデルと予約リストのモデルの定義

- app/api/katsumata/profile/route.ts
- prisma/schema.prisma
> StudentProfileテーブルに学年、希望勤務地カラムを追加

- app/api/koma/waitinglist/route.ts
- prisma/schema.prisma
GETが完成しました。
emailはコード内でダミーのアドレスを指定しているので、認証機能が完成次第更新します。
GETするデータがなかったので確認用にPUTも作成し、MongoDBでも確認可能です！
postmanでも問題なく動作確認できてるので多分OKです！
schemaの更新はDELETE用のものです。
> waitinglistのGETとテスト用POSTの作成(emailはハードコーディングして動作確認)waitinglistのschema更新

- app/api/katsumata/profile/route.ts
- app/api/katsumata/record/[id]/route.ts
- prisma/schema.prisma
> Feature katsumata

- prisma/schema.prisma
> add: スキーマのWaitingモデルをUserモデルの中に組み込みました。

- app/api/koma/waitinglist/route.ts
現状emailやidはハードコーディングでの実装。
PostmanとMongoDBで動作確認済みです。
> GETを新スキーマへの対応付け、DELETEの完成

- app/api/katsumata/approvallist/route.ts
- app/api/katsumata/record/[id]/route.ts
- prisma/schema.prisma
> approvallistAPI作成

- app/api/hagi/Booking/route.ts
- prisma/schema.prisma
BookingAPIのとりあえずの完成、スキーマのUserモデルの中に職員のプロフィールが記録できるように「StaffProfile」モデルを追加しました。確認お願いします。
> add: BookingAPIのとりあえずの完成、スキーマのUserモデルの中にStaffProfileモデルを追加

- app/api/hagi/Booking/route.ts
タイトル通りです。使っていなかったimport文の削除と、コメントを追加しました。コードは特にいじっていないので、コンフリクト等は発生しないと思いますが、確認お願いします。
> add: 細かいコメントの修正

- prisma/schema.prisma
プリズマスキーマファイルのWaitingListモデルのフィールド、staffEmailをstaffUserIdに変更しました。確認お願いします。
> add: プリズマスキーマのWaitingListモデルのフィールドの変更

- app/api/hagi/Booking/route.ts
> add: スキーマに合わせてAPIの変更。細かいコメントの追加

- prisma/schema.prisma
> change: プリズマスキーマファイルの変更

- prisma/schema.prisma
WaitingListのフィールドにstuentUserIdを追加。BookingListのフィールドのstudentEmailとstaffEmailの項目をstudentUserIdとstaffUserIdに変更
> change: スキーマの内容を変更しました

- app/api/hagi/Booking/route.ts
> clean: 細かいコメントの修正

- prisma/schema.prisma
スキーマのBookingコレクションにstudentNameとstaffNameという二つのフィールドを追加しました。
> add: スキーマの変更

- prisma/schema.prisma
WaitingListのフィールドにstudentnameとstaffnameの二つの項目を追加しました。
> add: スキーマファイルのWaitingListの項目を追加しました。

- app/api/hagi/Student/route.ts
- app/api/hagi/staff/route.ts
> add: 学生と職員用のホームAPI

- app/api/koma/ConfirmedRes/route.ts
- app/api/koma/StudentsListGet/route.ts
> add: 学生一覧取得API, 確定済み予約リスト取得API

- app/api/hagi/staff/ApiTest/route.ts
タイトル通り、承認待ちのWaitingListコレクションに存在する予定を、確定し、Bookingコレクションに追加するためのAPIを作成しました。確認お願いします。
> add: 承認待ちの予定を確定させるAPIの作成

- app/api/hagi/staff/route.ts
タイトル通りファイル内のコードをapi/hagi/staff/ApiTestファイルに移行しました。
> change: ファイル内でコメントアウトしていたコードを別ファイルに移行

- app/api/hagi/Booking/route.ts
タイトル通り、スキーマファイルでWaitingListコレクションに追加したレコードに合わせて、BookingApi内で値を追加する処理を追加しました。確認お願いします。
> add: スキーマファイルの変更に合わせて幾つか機能を追加

- app/api/koma/StudentsListGet/route.ts
> 学生一覧取得APIのリクエスト文の更新

- app/api/hagi/Student/route.ts
> add: 学生側ホーム画面でwaitingListの予定のidを返すように変更、waitingListにDELETEを追加

- app/(root)/student/page.tsx
- app/api/staff/record/route.ts
- app/api/student/route.ts
- prisma/schema.prisma
> 学生側ホーム画面の動的変換とrecordAPIの変更

- app/api/koma/StudentsListGet/route.ts
> 学生一覧取得API：学籍番号検索語に取得するレコードの追加

- app/(root)/staff/page.tsx
- app/(root)/student/page.tsx
- app/api/hagi/Student/route.ts
> 職員側ホーム画面動的変換

- app/api/hagi/Student/route.ts
タイトル通り、student側ホーム画面に返される予約済み予定データにscheduleId情報を追加しました。
> add: Student側ホーム画面に返される予約済み予定データにID情報を追加

- app/api/student/route.ts
> add: app/api/studentのAPIもscheduleIdを返すように機能を追加しました。

- app/(root)/staff/calendar/page.tsx
- app/(root)/staff/waitinglist/page.tsx
> waitinglistのロジック作成中

- app/api/koma/StudentsListGet/[id]/route.ts
- app/api/koma/StudentsListGet/route.ts
教員側画面で学生の一覧取得と検索するロジックが、どちらもGETなので別ファイルに分割しました。
> 学生一覧取得API(一覧取得と検索を分割)

- app/api/student/route.ts
タイトル通り、api/studentにDELETE機能を追加しました。
> add: api/studentにDELETE機能を追加

- app/api/koma/StudentsListGet/route.ts
> 学生一覧取得API:レスポンスからemail除去、変数名の更新

- app/(root)/student/page.tsx
学生側ホーム画面で予定存在していない場合メッセージが表示されるようになりました。キャンセル機能はまだ未実装です。
確認お願いします。
> add: 現段階でできている学生側ホーム画面のページ

- app/(root)/student/page.tsx
タイトル通りです。デザインに関してはまだまだ改善点ありです。
> add: 生徒側のホーム画面のキャンセル機能を追加

- app/api/student/booking/route.ts
> add: api/student/bookingのPOSTのAPIが古いものだったので更新しました。

- app/api/student/booking/route.ts
> change: コメントアウトされていた本番用の処理とテスト用の処理を切り替えました。

- app/api/staff/route.ts
> add: staff側ホーム画面のAPIの処理をテスト用から本番用の処理に切り替えました。

- app/api/student/route.ts
> add: API内の処理をテスト用から本番用に切り替えました。

- app/(root)/staff/studentsGet/page.tsx
エンドポイントはstaff/studentsGetなのでURL直打ちで画面確認してください。
> 学生一覧フロント画面設計にAPIの呼び出し処理を追加

- app/api/student/booking/route.ts
> add: 指名なしでも予約できるように機能追加

- app/(root)/staff/studentsGet/page.tsx
- app/api/koma/StudentsListGet/[id]/route.ts
- app/api/koma/StudentsListGet/route.ts
> 不要部分のコメントアウトと削除(学生一覧取得コンポーネントのフロントとバック)

- app/(root)/staff/studentsGet/page.tsx
検索ボックスに数値入力すると入力した瞬間にemailから部分一致するuserのみ表示する。
> 学生一覧コンポーネントの検索ロジック追加

- app/api/staff/approvallist/route.ts
> change: 処理が一部テスト時用のものだったので修正

- app/api/staff/approvallist/route.ts
> change: POSTの処理の中で処理が本番用に切り替わっていなかったので修正

- app/api/staff/approvallist/route.ts
- app/api/staff/calendar/route.ts
- app/api/staff/record/route.ts
- app/api/staff/route.ts
- app/api/student/route.ts
> update: API内のconsole.log文を削除しました。

- app/api/staff/approvallist/route.ts
> change: POSTの成功時のhttpステータスコードを201に修正

- app/api/staff/approvallist/route.ts
> add: POSTの処理の中にwaitingListを削除する処理を追加しました。

- app/api/staff/approvallist/nonominationList/route.ts
タイトル通りです。指名なしの予定を承認するためのAPIを作成しました。確認お願いします。
> add: 指名なし予定の承認用のAPI作成

- app/api/staff/calendar/route.ts
タイトル通りです。内容としては、bookingのデータを取得することができていなかったので、そこを修正しました。確認お願いします。
> change: calendarAPIのGETを修正しました。

- app/actions/getUserId.ts
> add: actionsに画面を操作しているユーザのidを取得する関数を追加

- app/api/staff/calendar/route.ts
> change: ハードコーティングされていた部分を変更

- app/api/staff/approvallist/nonominationList/route.ts
- app/api/staff/approvallist/route.ts
- app/api/staff/calendar/route.ts
- app/api/staff/route.ts
- app/api/student/route.ts
> change: 変更可能なAPIのidを取得する処理をactionsの関数を使用したものに変更

- app/api/staff/approvallist/nonominationList/route.ts
- app/api/staff/approvallist/route.ts
- app/api/staff/calendar/route.ts
- app/api/staff/record/route.ts
- app/api/staff/route.ts
- app/api/staff/students/route.ts
- app/api/student/booking/[id]/route.ts
- app/api/student/booking/route.ts
- app/api/student/bookingdelete/route.ts
- app/api/student/profile/route.ts
- app/api/student/route.ts
- app/api/student/waitdelete/route.ts
> change: API内のDB接続処理をactionsの関数を使用したものに置換しました。

- prisma/schema.prisma
waitinglistコレクションに予定が作成された日を記録できるようにドキュメントを追加しました。確認お願いします。誤ってブランチを削除してしまっていたので、再々プルリクエストになります。
> change: スキーマの変更

- app/api/staff/record/[id]/route.ts
> add: 指定されたidの学生の面談の履歴を取得するAPIの作成

- app/api/staff/calendar/route.ts
タイトル通りです。関数化されていたユーザのidを取得する処理を直接コード内に記述する形に変更しました。
> fix: 関数化されていたユーザのidを取得する処理を直接記述
